"""add is_deleted and fix drivers timestamp

Revision ID: 1c02cceca21e
Revises: 6f4382fb4af6
Create Date: 2026-09-09 09:27:28.095068

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql


revision: str = '1c02cceca21e'
down_revision: Union[str, None] = '6f4382fb4af6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drivers', sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    op.add_column('drivers', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('trips', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    op.add_column('vehicle_assignments', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='false'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicle_assignments', 'is_deleted')
    op.drop_column('users', 'is_deleted')
    op.drop_column('trips', 'is_deleted')
    op.add_column('drivers', sa.Column('creted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('drivers', 'is_deleted')
    op.drop_column('drivers', 'created_at')
    # ### end Alembic commands ###
