"""add drivers table

Revision ID: 4572e340ddc7
Revises: d98b94cb7c4c
Create Date: 2026-08-31 11:58:02.311097

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel




# revision identifiers, used by Alembic.
revision: str = '4572e340ddc7'
down_revision: Union[str, None] = 'd98b94cb7c4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('drivers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('license_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('license_expiry', sa.Date(), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='driverstatus'), nullable=False),
    sa.Column('creted_at', sa.DateTime(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_by', sa.Integer(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('license_number'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('drivers')
    # ### end Alembic commands ###
