"""add individual and company profile tables, clean users

Revision ID: 528ed437316e
Revises: 660c9e495fce
Create Date: 2026-09-14 15:21:55.819001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel




revision: str = '528ed437316e'
down_revision: Union[str, None] = '660c9e495fce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_owner_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_owner_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_registered_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rdb_certificate', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('individual_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('national_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.drop_column('users', 'certificate_url')
    op.drop_column('users', 'position')
    op.drop_column('users', 'date_of_birth')
    op.drop_column('users', 'company_name')
    op.drop_column('users', 'national_id_number')
    op.drop_column('users', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('national_id_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('date_of_birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('position', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('certificate_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_table('individual_profiles')
    op.drop_table('company_profiles')
    # ### end Alembic commands ###
