"""add national_id to users, update company_profiles, drop individual_profiles

Revision ID: 6c1803731e4b
Revises: 528ed437316e
Create Date: 2026-09-16 15:07:13.418067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

from sqlalchemy.dialects import postgresql


revision: str = '6c1803731e4b'
down_revision: Union[str, None] = '528ed437316e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.drop_table('individual_profiles')

    company_status_enum = sa.Enum(
        'sole_proprietorship', 'limited_company', 'partnership',
        name='companystatus'
    )
    company_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('company_profiles', sa.Column(
        'status', company_status_enum,
        nullable=False, server_default='limited_company'
    ))
    op.add_column('company_profiles', sa.Column(
        'is_deleted', sa.Boolean(),
        nullable=False, server_default='false'
    ))
    op.add_column('company_profiles', sa.Column(
        'deleted_at', sa.DateTime(), nullable=True
    ))
    op.drop_column('company_profiles', 'company_owner_first_name')
    op.drop_column('company_profiles', 'company_owner_last_name')

    op.add_column('users', sa.Column(
        'national_id_number', sqlmodel.sql.sqltypes.AutoString(), nullable=True
    ))
    op.add_column('users', sa.Column(
        'address', sqlmodel.sql.sqltypes.AutoString(), nullable=True
    ))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'address')
    op.drop_column('users', 'national_id_number')
    op.add_column('company_profiles', sa.Column('company_owner_last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('company_profiles', sa.Column('company_owner_first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_column('company_profiles', 'deleted_at')
    op.drop_column('company_profiles', 'is_deleted')
    op.drop_column('company_profiles', 'status')
    sa.Enum(name='companystatus').drop(op.get_bind(), checkfirst=True)    
    # ### end Alembic commands ###
