"""add is_delete column in model vehicle

Revision ID: acc6c6e670a8
Revises: 1c7febc0710a
Create Date: 2026-09-07 15:42:03.042969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel




revision: str = 'acc6c6e670a8'
down_revision: Union[str, None] = '1c7febc0710a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('vehicles', sa.Column('is_deleted', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vehicles', 'is_deleted')
    # ### end Alembic commands ###
